[parity]
chain = "demo-spec2.json"
base_path = "parity1"
[network]
port = 30301
reserved_peers = "bootnodes.txt"
[rpc]
port = 8541
apis = ["all"]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
[websockets]
port = 8451
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x1450b237f0c9dc260bf81942dbf988dd761baf83"
reseal_on_txs = "none"
force_sealing = true
reseal_min_period = 0
reseal_max_period = 10000
